spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.165:3307/tiendaformacion?serverTimezone=UTC
    username: root
    password: root   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-productos
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.165:8761/eureka
  instance: 
    hostname: 192.168.8.165
server:
  port: 8000 
